---

- name: Setup config internal facts
  ansible.builtin.set_fact:
    _proxy_client_http_config: >-
      {{ (proxy_client_http_proxy | default("", boolean=true) | length > 0)
        | ternary({"http_proxy": proxy_client_http_proxy,
                   "HTTP_PROXY": proxy_client_http_proxy}, {}) }}

    _proxy_client_https_config: >-
      {{ (proxy_client_https_proxy | default("", boolean=true) | length > 0)
        | ternary({"https_proxy": proxy_client_https_proxy,
                   "HTTPS_PROXY": proxy_client_https_proxy}, {}) }}

    _proxy_client_http_no_proxy: >-
      {{ (proxy_client_no_proxy | default([], boolean=true) | length > 0)
        | ternary({"no_proxy": proxy_client_no_proxy
                               | default("", boolean=true)
                               | join(","),
                   "NO_PROXY": proxy_client_no_proxy
                               | default("", boolean=true)
                               | join(",")}, {}) }}

- name: Setup environment value internal fact
  ansible.builtin.set_fact:
    _proxy_client_environment_value: >-
      {{ {}
         | combine((proxy_client_http_proxy | length > 0)
                   | ternary(_proxy_client_http_config, {}))
         | combine((ansible_facts.distribution_version | default("")
                    is version("7", ">=")
                    and proxy_client_https_proxy | length > 0)
                   | ternary(_proxy_client_https_config, {}))
         | combine((proxy_client_no_proxy | length > 0)
                   | ternary(_proxy_client_http_no_proxy, {})) }}
