---
# Role tasks

- block:
    - include_role:
        name: amtega.environment
      vars:
        environment_config:
          http_proxy: "{{ proxy_client_http_proxy }}"
          HTTP_PROXY: "{{ proxy_client_http_proxy }}"
          no_proxy: >-
            {{ proxy_client_no_proxy
               | default("", boolean=true)
               | join(',') }}
          NO_PROXY: >-
            {{ proxy_client_no_proxy
               | default("", boolean=true)
               | join(',') }}
      when: proxy_client_permanent

    - include_role:
        name: amtega.environment
      vars:
        environment_config:
          https_proxy: "{{ proxy_client_https_proxy }}"
          HTTPS_PROXY: "{{ proxy_client_https_proxy }}"
      when:
        - proxy_client_permanent
        - ansible_facts.distribution | default("") | lower in ['centos', 'rhel']
        - ansible_facts.distribution_version | default("") is version("7", ">=")

    - name: setup fact with proxy environment
      set_fact:
        proxy_client_environment: >-
          {{ http_config
             | combine((ansible_facts.distribution | default("")
                        | lower in ['centos', 'rhel']
                        and ansible_facts.distribution_version | default("")
                            is version("7", ">=")) | ternary(https_config, {}))
             | combine(http_no_proxy) }}
      vars:
        http_config: >-
          {{ (proxy_client_http_proxy | default("", boolean=true) | length > 0)
             | ternary({ "http_proxy": proxy_client_http_proxy,
                         "HTTP_PROXY": proxy_client_http_proxy }, {}) }}
        https_config: >-
          {{ (proxy_client_https_proxy | default("", boolean=true) | length > 0)
             | ternary({ "https_proxy": proxy_client_https_proxy,
                         "HTTPS_PROXY": proxy_client_https_proxy },
                       {}) }}
        http_no_proxy: >-
          {{ (proxy_client_no_proxy | default("", boolean=true) | length > 0)
             | ternary({ "no_proxy": proxy_client_no_proxy
                                     | default("", boolean=true)
                                     | join(","),
                         "NO_PROXY": proxy_client_no_proxy
                                     | default("", boolean=true)
                                     | join(",")}, {}) }}
  tags:
    - role::proxy_client
