---
# Role tasks

- name: assert platform is supported
  assert:
    that:
      - distribution in proxy_client_supported_distributions
      - >-
        ansible_facts.distribution_version
        is version(proxy_client_supported_versions[distribution], ">=")
  vars:
    distribution: "{{ ansible_facts.distribution | lower }}"
  tags:
    - role::proxy_client
    - role::proxy_client::check
