---

- name: Setup permanent proxy client
  block:
    - name: Setup permanent proxy client environment
      ansible.builtin.include_role:
        name: amtega.environment
      vars:
        environment_config: "{{ _proxy_client_environment_value }}"
        environment_skip_if_not_writeable: yes

    - name: Setup internal fact indicating that permanent proxy was configured
      ansible.builtin.set_fact:
        _proxy_client_permanent_configured: yes
  tags:
    - role::proxy_client
