---
# Role setup tasks

- block:
    - include_role:
        name: amtega.environment
      vars:
        environment_config:
          http_proxy: "{{ proxy_client_http_proxy }}"
          HTTP_PROXY: "{{ proxy_client_http_proxy }}"
          no_proxy: >-
            {{ proxy_client_no_proxy
               | default("", boolean=true)
               | join(',') }}
          NO_PROXY: >-
            {{ proxy_client_no_proxy
               | default("", boolean=true)
               | join(',') }}

    - include_role:
        name: amtega.environment
      vars:
        environment_config:
          https_proxy: "{{ proxy_client_https_proxy }}"
          HTTPS_PROXY: "{{ proxy_client_https_proxy }}"
      when:
        - >-
          ansible_facts.distribution | default("") | lower
          in ['centos', 'redhat']
        - ansible_facts.distribution_version | default("") is version("7", ">=")
  when: proxy_client_permanent | bool
  tags:
    - role::proxy_client
