---
# Role setup tasks

- name: Setup proxy client
  block:
    - name: Gather facts
      ansible.builtin.setup:
      when:
        - proxy_client_support_el_6 | bool
        - ansible_facts.os_family is undefined

    - ansible.builtin.include_tasks: permanent.yml
      when: proxy_client_permanent_value | bool

    - name: Setup facts with proxy environment
      ansible.builtin.set_fact:
        proxy_client_environment: "{{ proxy_client_environment_value }}"
        _proxy_client_permanent: "{{ proxy_client_permanent_value }}"
  tags:
    - role::proxy_client
