---

- name: Setup proxy client
  block:
    - name: Setup permanent proxy settings
      ansible.builtin.include_tasks: permanent.yml
      when: _proxy_client_permanent_value | bool

    - name: Setup facts with proxy environment
      ansible.builtin.set_fact:
        proxy_client_environment: "{{ _proxy_client_environment_value }}"
  tags:
    - role::proxy_client
